version: '3'

# TODO grafana is running on port 3000 which is annoying.  See if that can be changed
include:
  - docker-elk/docker-compose.yml
  - apisix-docker/example/docker-compose.yml  # when this is pushed to the cloud it will need to be changed for the different architecture

services:

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - weather

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./definitions.json:/etc/rabbitmq/definitions.json
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - weather

  boat-api:
    build: ./boat-api
    container_name: boat-api
    restart: always
    ports:
      - "3050:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb: 
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://sailor:sailor@rabbitmq:5672
      MONGODB_URI: mongodb://mongodb:27017/boats
      LOGSTASH_HOST: localhost      
      LOGSTASH_PORT: 5044
    networks:
      - weather

  point-forecast-service:
    build: ./point-forecast-service
    container_name: point-forecast-service
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://sailor:sailor@rabbitmq:5672
      LOGSTASH_HOST: localhost
      LOGSTASH_PORT: 5044
    networks:
      - weather       

  weather-api:
    build: ./weather-api
    container_name: weather-api
    restart: always
    ports:
      - "3200:3100"
    depends_on:
      point-forecast-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      mongodb: 
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://sailor:sailor@rabbitmq:5672
      MONGODB_URI: mongodb://mongodb:27017/boats
      LOGSTASH_HOST: localhost      
      LOGSTASH_PORT: 5044
    networks:
      - weather

  grib-downloader:
    build: ./grib-downloader
    container_name: grib-downloader
    restart: always
    ports:
      - "9231:9229" # map the debug port to the host machine
    volumes:
      - grib_data:/app/grib_files
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb: 
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://mongodb:27017/boats
      RABBITMQ_URL: amqp://sailor:sailor@rabbitmq:5672
      LOGSTASH_HOST: localhost
      LOGSTASH_PORT: 5044
    networks:
      - weather
  

volumes:
  mongodb_data:
  rabbitmq_data:
  grib_data:
  grafana_data:

networks:
  weather:
    driver: bridge