global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'boat-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['boat-service:3000']

  - job_name: 'grib-downloader'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grib-downloader:3000']