FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install

# The actual source code will be mounted as a volume

EXPOSE 3000

CMD ["npm", "run", "dev"]