name: Backend Chat CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push images
      run: |
        services=("weather-api" "weather-web" "nws-forecast-service" "boat-api" "grib-downloader")
        for service in "${services[@]}"; do
          docker buildx build \
            --file ./$service/Dockerfile \
            --push \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest \
            ./$service
        done

    - name: Clean up and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VM_SSH_HOST }}
        username: ${{ secrets.VM_SSH_USER }}
        key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/weather-service
          git pull origin main
          docker system prune -af --volumes
          docker compose down
          docker compose pull
          docker compose up -d
